### ISSUE TITLE
Turn or Stun server 

### ISSUE THREAD

**Issue by randydom** [0xLaurens/sendfa.st#18]
Do we need any turn or stun server ?

**Comment by 0xLaurens** [comment]
Yes you need to use a stun server. In frontend/src/lib/webrtc.ts, the STUN server is specified as follows: new RTCPeerConnection({iceServers: [{urls: "stun:stun.l.google.com:19302"}]}). Currently, I'm using Google's STUN servers, but alternatives like Cloudflare or Firefox servers can also be used.

**Comment by randydom** [comment]
Thank you , What about the NAT/Firewalls issues ?

**Comment by 0xLaurens** [comment]
STUN helps create NAT mappings, enabling incoming traffic through a network. However, if the firewall has very strict restrictions, the app may not function properly. TURN is a potential alternative, but it's costly to operate. Plus, I prefer direct peer-to-peer connections to ensure the privacy of each file transfer.

**Comment by randydom** [comment]
> STUN helps create NAT mappings, enabling incoming traffic through a network. However, if the firewall has very strict restrictions, the app may not function properly. TURN is a potential alternative, but it's costly to operate. Plus, I prefer direct peer-to-peer connections to ensure the privacy of each file transfer.
> 
> You might want to look at: https://webrtcforthecurious.com/docs/03-connecting/

Many thanks for that information ( which I already knew ) .
That's why I tried to say ( indirectly ) can you add - support - for a Turn server .
Again thank you .

**Comment by 0xLaurens** [comment]
If you want to run a version with a TURN server, you can add it to the URLs of the `RTCPeerConnection` located in `frontend/src/lib/webrtc.ts`. Adding a TURN server is out of scope.
